name: CI

on:
  pull_request:
    types: [opened, edited]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - arch: amd64
    name: Build on ${{ matrix.arch }}
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: Setup Docker
        run: |
          docker run --rm --privileged multiarch/qemu-user-static:register --reset

      - name: Setup build environment in Docker
        run: |
          docker run --workdir /github/workspace --rm --entrypoint "./01_setup_build_env.sh" -v "$(pwd)":"/github/workspace" multiarch/alpine:${{ matrix.arch }}-edge

      - name: Build static libnl3 in Docker
        run: |
          docker run --workdir /github/workspace --rm --entrypoint "./02_build_static_libnl3.sh" -v "$(pwd)":"/github/workspace" multiarch/alpine:${{ matrix.arch }}-edge

      - name: Build in Docker
        run: |
          docker run --workdir /github/workspace --rm --entrypoint "./03_build_static_alpine.sh" -v "$(pwd)":"/github/workspace" multiarch/alpine:${{ matrix.arch }}-edge

